config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations',
        passwords: 'users/passwords',
      }
  root "organizations#index"
  resources :organizations do
    resources :pics
  end
  get "/search", to: 'search#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/organization.rb
class Organization < ApplicationRecord
  has_attached_file :logo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :logo, content_type: /\Aimage\/.*\z/

  has_one :account_manager, foreign_key: 'organization_id'
  has_many :pics, class_name: 'Person', foreign_key: 'organization_id'

  def self.search(q)
    self.where("LOWER(name) LIKE LOWER(?)", "%#{q}%")
  end

end

app/models/person.rb
class Person < ApplicationRecord
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  belongs_to :organization

  def self.search(q)
    self.where("LOWER(name) LIKE LOWER(?)", "%#{q}%")
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def is_account_manager?
    self.organization_id.present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :authenticate_user!
  before_action :prepare_organization, only: [:edit, :show, :destroy, :update]

  def index
    @organizations = Organization.all
  end

  def new
    @organization = Organization.new
  end

  def create
    @organization = Organization.new(permitted_params)
    if @organization.save
      flash[:notice] = "Organization Successfully Created"
      update_organization(@organization.id)
      redirect_to edit_organization_path(@organization)
    else
      flash[:alert] = @organization.errors.full_messages
      render :new
    end
  end

  def edit
  end

  def update
    if @organization.update(permitted_params)
      flash[:notice] = "Organization Successfully Updated"
      redirect_to organizations_path
    else
      flash[:alert] = @organization.errors.full_messages
      render :edit
    end
  end

  def destroy
    if @organization.destroy
      flash[:notice] = "Organization Successfully Deleted"
      redirect_to organizations_path
    else
      flash[:alert] = @organization.errors.full_messages
      redirect_to organizations_path
    end
  end

  def show
    @pics = @organization.pics.all
  end

  private
    def permitted_params
      params.require(:organization).permit(:name, :email, :phone, :website, :logo, pics: [:id, :name, :phone, :email, :avatar, :_destroy])
    end

    def prepare_organization
      @organization = Organization.find(params[:id])
    end

    def update_organization(organization_id)
      User.where(id: current_user.id).update_all(organization_id: organization_id)
    end
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController
  before_action :authenticate_user!
  before_action :prepare_organization
  before_action :prepare_pic, only: [:edit, :show, :destroy, :update]

  def new
    @pic = @organization.pics.new
  end

  def create
    @pic = @organization.pics.new(permitted_params)
    if @pic.save
      flash[:notice] = "Pic Organization Successfully Created"
      redirect_to organization_path(@organization)
    else
      flash[:alert] = @pic.errors.full_messages
      render :new
    end
  end

  def edit
  end

  def update
    if @pic.update(permitted_params)
      flash[:notice] = "Pic Organization Successfully Updated"
      redirect_to organization_path(@organization)
    else
      flash[:alert] = @pic.errors.full_messages
      render :edit
    end
  end

  def destroy
    if @pic.destroy
      flash[:notice] = "Pic Organization Successfully Deleted"
      redirect_to organization_path(@organization)
    else
      flash[:alert] = @pic.errors.full_messages
      redirect_to organization_path(@organization)
    end
  end

  private
    def permitted_params
      params.require(:person).permit(:name, :phone, :email, :avatar)
    end

    def prepare_organization
      @organization = Organization.find(params[:organization_id])
    end

    def prepare_pic
      @pic = @organization.pics.find(params[:id])
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  before_action :authenticate_user!

  def index
    @pics = Person.search(params[:q])
    @organizations = Organization.search(params[:q])
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  layout 'layouts/login'
  
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  layout 'layouts/login'

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  layout 'layouts/login'
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Organization</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <%= render partial: 'pages/navbar' %>
      <%= render partial: 'pages/alert' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Login</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/organizations/_form.html.erb
<div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>
</div>
<div class="form-group">
  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>
</div>
<div class="form-group">
  <%= f.label :phone %>
  <%= f.text_field :phone, class: 'form-control' %>
</div>
<div class="form-group">
  <%= f.label :website %>
  <%= f.text_field :website, class: 'form-control' %>
</div>
<div class="form-group">
  <%= f.label :logo %>
  <%= f.file_field :logo, class: 'form-control' %>
</div>
<%= f.submit :Save, class: 'btn btn-primary' %>
<%= link_to "Back", organizations_path, class: "btn btn-info" %>

app/views/organizations/edit.html.erb
<div class="card">
  <div class="card-header">
    <h3> Edit Organization</h3>
  </div>
  <div class="card-body">
    <%= form_for(@organization, method: "put", html: {class: "form-horizontal margin-none"}) do |f| %>
      <%= render partial:"form", locals: {f: f} %>
    <% end %>
  </div>
</div>

app/views/organizations/index.html.erb
<div class="card">
  <div class="card-header">List Organization</div>
  <div class="card-body">
    <% if !current_user.is_account_manager? %>
      <a class="btn btn-primary pull-right" href="<%= new_organization_path %>">Add New</a>
    <% end %>
    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Name</th>
          <th scope="col">Website</th>
          <th scope="col">Action</th>
        </tr>
      </thead>
      <tbody>
        <% @organizations.each.with_index(1) do |org, no| %>
          <tr>
            <th scope="row"><%= no %></th>
            <td><%= org.name %></td>
            <td><%= org.website %></td>
            <td>
              <%= link_to 'Show', organization_path(org), class: "btn btn-info" %>
              <% if current_user.organization_id == org.id %>
                <%= link_to 'Edit', edit_organization_path(org), class: "btn btn-success" %>
                <%= link_to 'Delete', organization_path(org), method: "delete", class: "btn btn-danger" %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/organizations/new.html.erb
<div class="card">
  <div class="card-header">
    <h3> New Organization</h3>
  </div>
  <div class="card-body">
    <%= form_for(@organization, method: "post", html: {class: "form-horizontal"}) do |f| %>
     <%= render partial:"form", locals: {f: f} %>
    <% end %>
  </div>
</div>

app/views/organizations/show.html.erb
<div class="card">
  <div class="card-header">
    <h3>Detail <%= @organization.name %></h3>
  </div>
  <div class="card-body">
    <div><%= image_tag @organization.logo.url(:thumb) %></div>
    <div>Name : <%= @organization.name %></div>
    <div>Email : <%= @organization.email %></div>
    <div>Phone : <%= @organization.phone %></div>
    <div>Website : <%= @organization.website %></div>
    <h3>List PIC</h3>
    <%= link_to 'Add New', new_organization_pic_path(@organization), class: "btn btn-primary pull-right" %>
    <table class="table table-striped">
      <thead>
        <tr>
          <td>No</td>
          <td>Nama</td>
          <td>Email</td>
          <td>Phone</td>
          <td>Avatar</td>
          <% if current_user.organization_id == @organization.id %>
            <td>Action</td>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <% @pics.each.with_index(1) do |pic,no| %>
          <tr>
            <td><%= no %></td>
            <td><%= pic.name %></td>
            <td><%= pic.email %></td>
            <td><%= pic.phone %></td>
            <td><%= image_tag pic.avatar.url(:thumb) %></td>
            <% if current_user.organization_id == @organization.id %>
              <td>
                <%= link_to 'Edit', edit_organization_pic_path(@organization,pic), class: "btn btn-success" %>
                <%= link_to 'Delete', organization_pic_path(@organization,pic), method: "delete", class: "btn btn-danger", data: { confirm: 'Are You Sure'} %>
              </td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

</div>

app/views/pages/_alert.html.erb
<% if flash[:notice].present? %>
  <div class="alert alert-primary alert-dismissible fade show" role="alert">
    <%= raw(flash[:notice]) %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if flash[:alert].present? %>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <%= raw(flash[:alert]) %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/pages/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="<%= root_path %>">Organization Printerous</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
  </div>
  <%= link_to "#{current_user.name} - Logout", destroy_user_session_path, method: 'delete', class: 'btn btn-danger' %>
  <form action="/search" class="form-inline my-2 my-lg-0">
    <input class="form-control mr-sm-2" name="q" placeholder="Search" aria-label="Search">
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
  </form>
</nav>

app/views/pics/_form.html.erb
<div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>
</div>
<div class="form-group">
  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>
</div>
<div class="form-group">
  <%= f.label :phone %>
  <%= f.text_field :phone, class: 'form-control' %>
</div>
<div class="form-group">
  <%= f.label :avatar %>
  <%= f.file_field :avatar, class: 'form-control' %>
</div>
<%= f.submit :Save, class: 'btn btn-primary' %>
<%= link_to "Back", organization_path(@organization), class: "btn btn-info" %>

app/views/pics/edit.html.erb
<div class="row">
  <div class="tab-content" style="padding: 0;">
    <div class="hr_title">
      <h3> Edit Pic </h3>
    </div>
    <%= form_for(@organization, method: "put", html: {class: "form-horizontal margin-none"}) do |f| %>
      <%= render partial:"form", locals: {f: f} %>
    <% end %>
  </div>
</div>

app/views/pics/new.html.erb
<div class="card">
  <div class="card-header">
    <h3> <%= "New PIC on #{@organization.name}" %></h3>
  </div>
  <div class="card-body">
    <%= form_for(@pic, url: organization_pics_path, method: "post", html: {class: "form-horizontal"}) do |f| %>
     <%= render partial:"form", locals: {f: f} %>
    <% end %>
  </div>
</div>

app/views/search/index.html.erb
<div class="card">
  <% if @pics.present? %>
    <div class="card-header">
      <h3> Result Searching Person </h3>
    </div>
    <div class="card-body">
      <ol>
        <% @pics.each do |pic| %>
          <li>
            <%= link_to pic.name, edit_organization_pic_path(pic.organization_id, pic.id) %>
          </li>
        <% end %>
      </ol>
    </div>
  <% end %>
  <% if @organizations.present? %>
    <div class="card-header">
      <h3> Result Searching Organization </h3>
    </div>
    <div class="card-body">
      <ol>
        <% @organizations.each do |org| %>
          <li>
            <%= link_to org.name, organization_path(org) %>
          </li>
        <% end %>
      </ol>
    </div>
  <% end %>
</div>